---
apiVersion: v1
kind: Pod
metadata:
  name: mydb
  labels:
    type: webserver
    author: vishnu
spec:
  containers:
    - name: mysql
      image: mysql
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: vishnu

         
