---
apiVersion: v1
kind: Pod
metadata:
  name: tomcat-pod
  namespace: test-ns
  labels:
    type: appserver
    author: vishnu
spec:
  containers:
    - name: mytomee
      image: tomee
      ports:
        - containerPort: 8080
          hostPort: 8080
...
