---
apiVersion: v1
kind: Pod
metadata:
  name: httpd-pod
  labels:
    type: appserver
    author: vishnu
spec:
  containers:
    - name: myhttpd
      image: httpd
      ports:
        - containerPort: 80
          hostPort: 8080
...

